const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Behaviors.lunarray_LiteTween,
		C3.Plugins.Arr,
		C3.Behaviors.Pin,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Plugins.Function,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.lunarray_LiteTween.Acts.SetTarget,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.XAt,
		C3.Plugins.Touch.Exps.TouchIndex,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.lunarray_LiteTween.Cnds.OnEnd,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.lunarray_LiteTween.Acts.Reverse,
		C3.Behaviors.lunarray_LiteTween.Cnds.IsActive,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.lunarray_LiteTween.Cnds.OnReverseEnd,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Spritefont2.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Spritefont2.Cnds.CompareText,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Spritefont2.Acts.MoveToLayer,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsInvite,
		C3.Plugins.LocalStorage.Cnds.CompareKey,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Spritefont2.Acts.SetCharacterWidth,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.loopindex
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Touch: 0},
	{Browser: 0},
	{ScrollTo: 0},
	{Sine: 0},
	{loading: 0},
	{desk: 0},
	{combo: 0},
	{onPunch: 0},
	{Sine2: 0},
	{redbox: 0},
	{bluebox: 0},
	{punched: 0},
	{which: 0},
	{score: 0},
	{tall: 0},
	{trueor: 0},
	{theRabbit: 0},
	{hitfx: 0},
	{camera: 0},
	{Fade: 0},
	{LiteTween: 0},
	{"30bBlue": 0},
	{"30bRed": 0},
	{"25b": 0},
	{"19b": 0},
	{"30bImport": 0},
	{"30bPurple": 0},
	{Pin: 0},
	{Bullet: 0},
	{Rotate: 0},
	{bunnyAp: 0},
	{magician: 0},
	{"30bYellow": 0},
	{cloud: 0},
	{white: 0},
	{Function: 0},
	{title: 0},
	{stand: 0},
	{Синусоид: 0},
	{buttons: 0},
	{player1: 0},
	{player2: 0},
	{blue: 0},
	{orange: 0},
	{blackTransition: 0},
	{soundButton: 0},
	{tutoTouch: 0},
	{ready: 0},
	{go: 0},
	{Keyboard: 0},
	{blueLast: 0},
	{redLast: 0},
	{timeisup: 0},
	{menubutton: 0},
	{winDraw: 0},
	{whiteLast: 0},
	{LocalStorage: 0},
	{GamePush: 0},
	{"30b": 0},
	{punchTeam: 0},
	{endTexts: 0},
	{time130: 0},
	{best: 0},
	{score2: 0},
	{sound: 0},
	{can: 0},
	{x: 0},
	{punchRange: 0},
	{Speed: 0},
	{player: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	loading: class extends self.ISpriteInstance {},
	desk: class extends self.ISpriteInstance {},
	redbox: class extends self.ISpriteInstance {},
	bluebox: class extends self.ISpriteInstance {},
	theRabbit: class extends self.ISpriteInstance {},
	hitfx: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	_30bBlue: class extends self.ISpriteFontInstance {},
	_30bRed: class extends self.ISpriteFontInstance {},
	_25b: class extends self.ISpriteFontInstance {},
	_19b: class extends self.ISpriteFontInstance {},
	_30bImport: class extends self.IArrayInstance {},
	_30bPurple: class extends self.ISpriteFontInstance {},
	bunnyAp: class extends self.ISpriteInstance {},
	magician: class extends self.ISpriteInstance {},
	_30bYellow: class extends self.ISpriteFontInstance {},
	cloud: class extends self.ISpriteInstance {},
	white: class extends self.ISpriteFontInstance {},
	Function: class extends self.IInstance {},
	title: class extends self.ISpriteInstance {},
	stand: class extends self.ISpriteInstance {},
	buttons: class extends self.ISpriteInstance {},
	player1: class extends self.ISpriteInstance {},
	player2: class extends self.ISpriteInstance {},
	blue: class extends self.ISpriteInstance {},
	orange: class extends self.ISpriteInstance {},
	blackTransition: class extends self.ITiledBackgroundInstance {},
	soundButton: class extends self.ISpriteInstance {},
	tutoTouch: class extends self.ISpriteInstance {},
	ready: class extends self.ISpriteInstance {},
	go: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	blueLast: class extends self.ITiledBackgroundInstance {},
	redLast: class extends self.ITiledBackgroundInstance {},
	timeisup: class extends self.ISpriteInstance {},
	menubutton: class extends self.ISpriteInstance {},
	winDraw: class extends self.ISpriteInstance {},
	whiteLast: class extends self.ITiledBackgroundInstance {},
	LocalStorage: class extends self.IInstance {},
	GamePush: class extends C3.Plugins.Eponesh_GameScore.Instance {},
	_30b: class extends self.ISpriteFontInstance {},
	punchTeam: class extends self.ISpriteInstance {},
	endTexts: class extends self.ISpriteInstance {}
}