const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Sprite,
		C3.Behaviors.lunarray_LiteTween,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Plugins.Spritefont2,
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Eponesh_GameScore,
		C3.Behaviors.Sin,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Button.Acts.SetPos,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardOpen,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Behaviors.lunarray_LiteTween.Cnds.OnEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.CompareTouchSpeed,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Touch.Exps.AngleAt,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Behaviors.lunarray_LiteTween.Acts.SetTweenedProperty,
		C3.Behaviors.lunarray_LiteTween.Acts.SetTarget,
		C3.Behaviors.lunarray_LiteTween.Acts.SetDuration,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Spritefont2.Acts.SetPosToObject,
		C3.Plugins.Spritefont2.Acts.MoveToTop,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.IsClockwiseFrom,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Cnds.CompareY,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSetScore,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsInvite,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Behaviors.Fade.Cnds.OnFadeInEnd
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Browser: 0},
	{LiteTween: 0},
	{Flash: 0},
	{Player: 0},
	{Colors: 0},
	{Id: 0},
	{Platform: 0},
	{Keyboard: 0},
	{ScoreText: 0},
	{Point: 0},
	{SpriteFont: 0},
	{TiledBackground: 0},
	{Collision: 0},
	{Collision2: 0},
	{Collision3: 0},
	{Collision4: 0},
	{Pause: 0},
	{Fade: 0},
	{Fade2: 0},
	{GameName: 0},
	{SoundButton: 0},
	{Sprite: 0},
	{Particles: 0},
	{Point2: 0},
	{Particles2: 0},
	{Particles3: 0},
	{Particles4: 0},
	{Particles5: 0},
	{Particles6: 0},
	{Particles7: 0},
	{Particles8: 0},
	{TiledBackground3: 0},
	{TiledBackground4: 0},
	{Score: 0},
	{HighScore: 0},
	{TiledBackground2: 0},
	{Play: 0},
	{Sound2: 0},
	{Audio: 0},
	{Arrow: 0},
	{TextGo: 0},
	{Point3: 0},
	{TextGo2: 0},
	{Point5: 0},
	{TextTime: 0},
	{Score2: 0},
	{ЛокальноеХранилище: 0},
	{GamePush: 0},
	{ЧисловойЛабиринт: 0},
	{Синусоид: 0},
	{buttons: 0},
	{FADE: 0},
	{FADE2: 0},
	{I: 0},
	{INFO: 0},
	{вид: 0},
	{бан: 0},
	{Family1: 0},
	{Family2: 0},
	{Dead: 0},
	{Start2: 0},
	{Start: 0},
	{GameOver: 0},
	{Possition: 0},
	{IsSwiping: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Player: class extends self.ISpriteInstance {},
	Platform: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	ScoreText: class extends self.ISpriteFontInstance {},
	Point: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Collision: class extends self.ISpriteInstance {},
	Collision2: class extends self.ISpriteInstance {},
	Collision3: class extends self.ISpriteInstance {},
	Collision4: class extends self.ISpriteInstance {},
	Pause: class extends self.ISpriteInstance {},
	GameName: class extends self.ISpriteInstance {},
	SoundButton: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Point2: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Particles4: class extends self.IParticlesInstance {},
	Particles5: class extends self.IParticlesInstance {},
	Particles6: class extends self.IParticlesInstance {},
	Particles7: class extends self.IParticlesInstance {},
	Particles8: class extends self.IParticlesInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Score: class extends self.ISpriteFontInstance {},
	HighScore: class extends self.ISpriteFontInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Play: class extends self.ISpriteInstance {},
	Sound2: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Arrow: class extends self.ISpriteInstance {},
	TextGo: class extends self.ISpriteFontInstance {},
	Point3: class extends self.ISpriteInstance {},
	TextGo2: class extends self.ISpriteFontInstance {},
	Point5: class extends self.ISpriteInstance {},
	TextTime: class extends self.ISpriteFontInstance {},
	Score2: class extends self.ISpriteFontInstance {},
	ЛокальноеХранилище: class extends self.IInstance {},
	GamePush: class extends self.IInstance {},
	ЧисловойЛабиринт: class extends self.ISpriteInstance {},
	buttons: class extends self.ISpriteInstance {},
	I: class extends self.ISpriteInstance {},
	INFO: class extends self.ISpriteInstance {},
	вид: class extends self.IButtonInstance {},
	бан: class extends self.IButtonInstance {},
	Family1: class extends self.ISpriteInstance {},
	Family2: class extends self.ISpriteInstance {}
}